import React, { useEffect, useState } from "react";
import { Card, CardContent } from "../../../../components/ui/card";
import { supabase } from "../../../../lib/supabase";
import { sendAdminNotification, sendClientConfirmation } from "../../../../lib/emailjs";

type Testimonial = {
  quote: string;
  author: string;
  company: string;
};

const testimonials: Testimonial[] = [
  {
    quote: "OWL AI has become the backbone of our research function.",
    author: "Director",
    company: "Global Asset Management Firm"
  },
  {
    quote: "OWL's partnership approach to making insights available for our customers is truly unique. OWL has understood our specific needs and those of our customers and helped deliver accessible and useful data.",
    author: "Marshall Smith, CIPM",
    company: "Chief Operating Officer | FirstRate"
  },
  {
    quote: "10x faster insight generation with enterprise-grade security.",
    author: "Head of Research",
    company: "Hedge Fund"
  },
  {
    quote: "OWL's data-based research and fundamental insights allow us to enhance our investment solutions.",
    author: "Shoichiro Aoyama",
    company: "Fund Manager, Index Solution Group | Asset Management One Co.,Ltd."
  },
  {
    quote: "Finally, AI that understands financial nuance and compliance.",
    author: "Chief Investment Officer",
    company: "Pension Fund"
  },
  {
    quote: "The real-time data processing and AI-driven analysis have transformed how we approach market research and investment decisions.",
    author: "Sarah Chen",
    company: "Director of Research | Global Investment Advisors"
  },
  {
    quote: "Seamless integration with our existing data infrastructure.",
    author: "CTO",
    company: "Asset Management"
  },
  {
    quote: "Our analysts can now focus on alpha generation, not data collection.",
    author: "Portfolio Manager",
    company: "Investment Firm"
  }
];

export const Section05_Reviews = (): JSX.Element => {
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const [opacity, setOpacity] = useState(1);
  const [isHovered, setIsHovered] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    telephone: '',
    problems: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitStatus, setSubmitStatus] = useState<{
    type: 'success' | 'error' | null;
    message: string;
  }>({ type: null, message: '' });

  useEffect(() => {
    if (isHovered) return; // Don't auto-advance when hovered

    const interval = setInterval(() => {
      setOpacity(0);
      setTimeout(() => {
        setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
        setOpacity(1);
      }, 300); // Fade out duration
    }, 4000); // Change every 4 seconds

    return () => clearInterval(interval);
  }, [isHovered]);

  const handleTestimonialChange = (index: number) => {
    setOpacity(0);
    setTimeout(() => {
      setCurrentTestimonial(index);
      setOpacity(1);
    }, 300);
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
    // Immediately change to next testimonial when hovering out
    setOpacity(0);
    setTimeout(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
      setOpacity(1);
    }, 300);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitStatus({ type: null, message: '' });

    try {
      // Try inserting without .select() first to see if table exists
      const { data, error } = await supabase
        .from('owl_ai_contact_submissions')
        .insert({
          name: formData.name,
          email: formData.email,
          telephone: formData.telephone,
          problems: formData.problems || null
          // created_at is auto-generated by the database
        })
        .select();

      if (error) {
        console.error('Supabase error details:', {
          message: error.message,
          details: error.details,
          hint: error.hint,
          code: error.code,
          fullError: JSON.stringify(error, null, 2)
        });
        throw error;
      }

      // Send emails via EmailJS (non-blocking)
      // Using same client confirmation template for both forms
      const emailData = {
        name: formData.name,
        email: formData.email,
        telephone: formData.telephone,
        company: "", // Not in contact form
        title: "", // Not in contact form
      };
      
      Promise.all([
        sendAdminNotification(emailData),
        sendClientConfirmation(emailData)
      ]).catch(err => {
        console.warn('Email sending failed (non-critical):', err);
      });

      // Success
      setSubmitStatus({
        type: 'success',
        message: 'Thank you! We\'ll get back to you soon.'
      });
      
      // Reset form after successful submission
      setFormData({ name: '', email: '', telephone: '', problems: '' });
      
      // Clear success message after 5 seconds
      setTimeout(() => {
        setSubmitStatus({ type: null, message: '' });
      }, 5000);
    } catch (error: any) {
      console.error('Error submitting form:', error);
      console.error('Error type:', typeof error);
      console.error('Error keys:', Object.keys(error || {}));
      console.error('Full error object:', JSON.stringify(error, null, 2));
      
      // Provide more helpful error messages
      let errorMessage = 'Something went wrong. Please try again.';
      
      // Check for 404 or table not found errors
      if (
        error?.code === 'PGRST116' || 
        error?.message?.includes('404') || 
        error?.message?.includes('does not exist') ||
        error?.message?.includes('relation') ||
        !error // Empty error object often means 404
      ) {
        errorMessage = 'Table "owl_ai_contact_submissions" not found. Please verify:\n1. The table exists in your Supabase database\n2. The table name is exactly "owl_ai_contact_submissions"\n3. The table is set to unrestricted (RLS disabled)';
      } else if (error?.message) {
        errorMessage = error.message;
      } else if (error?.details) {
        errorMessage = error.details;
      } else if (error?.hint) {
        errorMessage = error.hint;
      } else {
        errorMessage = 'Unable to connect to database. Please check your Supabase configuration.';
      }
      
      setSubmitStatus({
        type: 'error',
        message: errorMessage
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <section
      className="flex flex-col w-full items-start gap-6 md:gap-10 px-6 md:px-14 py-8 md:py-16"
      aria-label="Section 5 — Results"
    >
      {/* Heading */}
      <div className="flex items-center w-full">
        <div className="flex flex-col w-6 h-2 items-start pr-4">
          <div className="w-2 h-2 bg-wezomcomblack rounded" />
        </div>
        <div className="[font-family:'Manrope',Helvetica] font-semibold text-wezomcomblack text-xs md:text-[13px] leading-4">
          THE RESULTS
        </div>
      </div>

      {/* Metrics */}
      <div className="mt-2 grid grid-cols-1 md:grid-cols-3 gap-6 w-full">
        <Card className="border border-[#afafaf60] rounded-xl bg-white/70 backdrop-blur-sm shadow-sm">
          <CardContent className="p-6 md:p-8">
            <div className="text-4xl font-bold text-wezomcomblack">10x</div>
            <div className="text-sm text-wezomcomdove-gray mt-1">Analyst productivity</div>
          </CardContent>
        </Card>
        <Card className="border border-[#afafaf60] rounded-xl bg-white/70 backdrop-blur-sm shadow-sm">
          <CardContent className="p-6 md:p-8">
            <div className="text-4xl font-bold text-wezomcomblack">75%</div>
            <div className="text-sm text-wezomcomdove-gray mt-1">Faster insight generation</div>
          </CardContent>
        </Card>
        <Card className="border border-[#afafaf60] rounded-xl bg-white/70 backdrop-blur-sm shadow-sm">
          <CardContent className="p-6 md:p-8">
            <div className="text-4xl font-bold text-wezomcomblack">15%</div>
            <div className="text-sm text-wezomcomdove-gray mt-1">Higher data accuracy</div>
          </CardContent>
        </Card>
      </div>

      {/* Testimonials Carousel */}
      <div className="mt-6 w-full">
        <div
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={handleMouseLeave}
          className="w-full rounded-xl border border-[#afafaf60] bg-white/70 backdrop-blur-sm p-4 sm:p-6 md:p-8 min-h-[140px] sm:h-[180px] md:h-[200px] lg:h-[220px] flex items-center hover:bg-white/90 hover:border hover:border-[#afafaf90] transition-all duration-300 text-left"
        >
          <blockquote 
            className="[font-family:'Manrope',Helvetica] text-wezomcomblack/90 text-sm sm:text-base md:text-lg leading-6 sm:leading-7 md:leading-8 transition-opacity duration-300 ease-in-out w-full"
            style={{ opacity }}
          >
            "{testimonials[currentTestimonial].quote}"
            <span className="block mt-2 text-xs sm:text-sm text-wezomcomdove-gray">
              — {testimonials[currentTestimonial].author}, {testimonials[currentTestimonial].company}
            </span>
          </blockquote>
        </div>
        
        {/* Dots indicator */}
        <div className="flex justify-center mt-4 space-x-2">
          {Array.from({ length: 4 }).map((_, index) => {
            const isActive = (currentTestimonial % 4) === index;
            return (
              <button
                key={index}
                onClick={() => handleTestimonialChange(index)}
                className={`w-2 h-2 rounded-full transition-colors duration-300 ${
                  isActive ? 'bg-wezomcomblack' : 'bg-gray-300'
                }`}
                aria-label={`Go to testimonial group ${index + 1}`}
              />
            );
          })}
        </div>
      </div>

      {/* Contact Form */}
      <div className="mt-8 md:mt-12 w-full">
        <Card className="border border-[#afafaf60] rounded-xl bg-white/70 backdrop-blur-sm shadow-sm">
          <CardContent className="p-6 md:p-8">
            <h3 className="text-2xl md:text-3xl font-bold text-wezomcomblack mb-6 tracking-tight [font-family:'Manrope',Helvetica]">
              Get in Touch
            </h3>
            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
              {/* Name Field */}
              <div className="flex flex-col gap-2">
                <label htmlFor="name" className="text-sm md:text-base font-semibold text-wezomcomblack [font-family:'Manrope',Helvetica]">
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  placeholder="Enter your name"
                  required
                  className="cursor-target w-full px-4 py-3 rounded-xl border border-[#afafaf80] bg-white text-wezomcomblack text-sm md:text-base hover:border-wezomcomblack focus:outline-none focus:border-wezomcomblack transition-colors [font-family:'Manrope',Helvetica]"
                />
              </div>

              {/* Email Field */}
              <div className="flex flex-col gap-2">
                <label htmlFor="email" className="text-sm md:text-base font-semibold text-wezomcomblack [font-family:'Manrope',Helvetica]">
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  placeholder="Enter your email"
                  required
                  className="cursor-target w-full px-4 py-3 rounded-xl border border-[#afafaf80] bg-white text-wezomcomblack text-sm md:text-base hover:border-wezomcomblack focus:outline-none focus:border-wezomcomblack transition-colors [font-family:'Manrope',Helvetica]"
                />
              </div>

              {/* Telephone Field */}
              <div className="flex flex-col gap-2">
                <label htmlFor="telephone" className="text-sm md:text-base font-semibold text-wezomcomblack [font-family:'Manrope',Helvetica]">
                  Telephone Number
                </label>
                <input
                  type="tel"
                  id="telephone"
                  name="telephone"
                  value={formData.telephone}
                  onChange={handleInputChange}
                  placeholder="Enter your telephone number"
                  required
                  className="cursor-target w-full px-4 py-3 rounded-xl border border-[#afafaf80] bg-white text-wezomcomblack text-sm md:text-base hover:border-wezomcomblack focus:outline-none focus:border-wezomcomblack transition-colors [font-family:'Manrope',Helvetica]"
                />
              </div>

              {/* Problems/Challenges Field - Optional */}
              <div className="flex flex-col gap-2">
                <label htmlFor="problems" className="text-sm md:text-base font-semibold text-wezomcomblack [font-family:'Manrope',Helvetica]">
                  What are the problems you're looking to solve with our software?
                  <span className="text-gray-400 text-xs font-normal ml-1">(Optional)</span>
                </label>
                <p className="text-xs text-gray-500 [font-family:'Manrope',Helvetica]">
                  Help us understand your needs better by sharing the challenges you're facing. This information will help us prepare a more tailored demo for you.
                </p>
                <textarea
                  id="problems"
                  name="problems"
                  value={formData.problems}
                  onChange={handleInputChange}
                  rows={4}
                  placeholder="Tell us about your challenges (Optional)"
                  className="cursor-target w-full px-4 py-3 rounded-xl border border-[#afafaf80] bg-white text-wezomcomblack text-sm md:text-base hover:border-wezomcomblack focus:outline-none focus:border-wezomcomblack transition-colors [font-family:'Manrope',Helvetica] resize-none"
                />
              </div>

              {/* Status Message */}
              {submitStatus.type && (
                <div
                  className={`p-4 rounded-xl ${
                    submitStatus.type === 'success'
                      ? 'bg-green-50 border border-green-200 text-green-800'
                      : 'bg-red-50 border border-red-200 text-red-800'
                  } [font-family:'Manrope',Helvetica] text-sm md:text-base`}
                >
                  {submitStatus.message}
                </div>
              )}

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full px-6 py-3 rounded-xl bg-wezomcomblack text-white font-semibold text-base md:text-lg hover:bg-transparent hover:text-wezomcomblack hover:border hover:border-[#afafaf80] disabled:bg-gray-400 disabled:cursor-not-allowed transition-all duration-300 shadow-lg [font-family:'Manrope',Helvetica]"
              >
                {isSubmitting ? 'Submitting...' : 'Submit'}
              </button>
            </form>
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default Section05_Reviews;